### ISSUE TITLE
where i should add telegram bot token ?

### ISSUE THREAD

**Issue by rsoorajs** [eidoriantan/messenger-translator-telegram#5]
First off all a huge thanks for making an amazing bot...i checked and its just amazing.

bro can you mention the file & line which i have to add my telegram bot token ?

**Comment by eidoriantan** [comment]
You can just set an environment variable named "BOT_TOKEN"

**Comment by eidoriantan** [comment]
Anyway, it's [here](https://github.com/eidoriantan/messenger-translator-telegram/blob/7166a40fb022e14ed5a2abfb53660b9776df88ab/server.js#L30)
