### ISSUE TITLE
Getting database error while deploy to heroku

### ISSUE THREAD

**Issue by rsoorajs** [eidoriantan/messenger-translator-telegram#6]
`2021-01-17T02:21:06.141650+00:00 app[web.1]:     at Object.urlParse [as parse] (node:url:156:13)
2021-01-17T02:21:06.141651+00:00 app[web.1]:     at TeleBot.module.exports (/app/node_modules/telebot/lib/webhook.js:12:22)
2021-01-17T02:21:06.141652+00:00 app[web.1]:     at /app/node_modules/telebot/lib/telebot.js:169:32
2021-01-17T02:21:06.141652+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
2021-01-17T02:21:06.141653+00:00 app[web.1]:   code: 'ERR_INVALID_ARG_TYPE'
2021-01-17T02:21:06.141655+00:00 app[web.1]: }
2021-01-17T02:21:06.259004+00:00 heroku[web.1]: Process exited with status 0
2021-01-17T02:21:06.318916+00:00 heroku[web.1]: State changed from starting to crashed
2021-01-17T02:24:33.539223+00:00 app[api]: Scaled to web@0:Free by user e40nu408@thromail.com
2021-01-17T02:24:33.770795+00:00 heroku[web.1]: State changed from crashed to down`

i am getting this error in heroku.

![IMG_20210117_080621_861](https://user-images.githubusercontent.com/20116017/104829570-2e022600-589b-11eb-9f23-b94a52eb6ee4.jpg) 

![IMG_20210117_080624_002](https://user-images.githubusercontent.com/20116017/104829566-2b9fcc00-589b-11eb-9326-d267d4ba6b74.jpg)

**Comment by eidoriantan** [comment]
You should also define an environment variable called URL having a value like "https://xxx.herokuapp.com" (please note that it should not end with a trailing `/`).

Also, the bot uses SQL server (Microsoft SQL Server) for managing user's data

**Comment by rsoorajs** [comment]
> You should also define an environment variable called URL having a value like "https://xxx.herokuapp.com" (please note that it should not end with a trailing `/`).
> 
> Also, the bot uses SQL server (Microsoft SQL Server) for managing user's data

so postegres sql database doesnt gonna work ?

**Comment by eidoriantan** [comment]
I haven't tried it myself so I'm not really sure. But by reading [this](https://wiki.postgresql.org/wiki/Microsoft_SQL_Server_to_PostgreSQL_Migration_by_Ian_Harding), I guess it won't work and you'll have to migrate to Postegres if you wanted to use it.

**Comment by rsoorajs** [comment]
![IMG_20210117_200935_835](https://user-images.githubusercontent.com/20116017/104846374-2de84180-5900-11eb-9d2e-2052117bcb5d.jpg)

why dont you try an easier dbs likeb postgress or mongodb..any heroku db addon is working with your code ?

or should i have to install mysql like this..postegres was much easier..

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15

**Comment by rsoorajs** [comment]
can you dockerise the code ? That will be helpful..then i can run it on heroku or https://uffizzi.com

**Comment by eidoriantan** [comment]
In my case, I can't use an add-on with my Heroku because I'm not verified yet. I use Microsoft's SQL Server since it's free because I have [GitHub Education Discount](https://education.github.com).

**Comment by eidoriantan** [comment]
> can you dockerise the code ? That will be helpful..then i can run it on heroku or https://uffizzi.com

I'm sorry but I'm not quite familiar with docker.

If you really like to use other RDBMS, you can always open a pull request. Thank you for your interest!
